### ISSUE TITLE
(FunctionClauseError) no function clause matching in anonymous fn/2 in Plug.Conn.merge_resp_headers/2

### ISSUE THREAD

**Issue by awwong1** [mschae/cors_plug#40]
After upgrading from `1.3` to `1.4` I'm getting the following errors in my Phoenix application.

I've included a snippet of the error that shows up when I run my tests:

```text
  1) test does not update chosen user and renders errors when user is invalid (Udia.Web.UserControllerTest)
     test/udia/web/controllers/user_controller_test.exs:154
     ** (FunctionClauseError) no function clause matching in anonymous fn/2 in Plug.Conn.merge_resp_headers/2
     stacktrace:
       (plug) lib/plug/conn.ex:663: anonymous fn({"access-control-allow-origin", nil}, [{"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", "n988irgthhkv295okfquhdg4tq9rh3dj"}, {"vary", "Origin"}]) in Plug.Conn.merge_resp_headers/2
       (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
       (plug) lib/plug/conn.ex:663: Plug.Conn.merge_resp_headers/2
       (cors_plug) lib/cors_plug.ex:33: CORSPlug.call/2
       (udia) lib/udia/web/endpoint.ex:1: Udia.Web.Endpoint.plug_builder_call/2
       (udia) lib/udia/web/endpoint.ex:1: Udia.Web.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/udia/web/controllers/user_controller_test.exs:156: (test)
```

**Comment by mschae** [comment]
Sorry for the late reply @awwong1. It looks like origin is coming back with `nil` which it shouldn't. To help me debug this, could you point me to what you `origin` is configured at?

BTW: This is a good error. :) `nil` is not a valid header so I'm glad the latest update surfaces this.

**Comment by awwong1** [comment]
Sorry for the late reply, I had a bug in my code where I did not set my cors plug origin properly. After setting it properly and running the tests again, I can verify that there are no issues.
