### ISSUE TITLE
Anonymous function to :origin isn't possible

### ISSUE THREAD

**Issue by anthonator** [mschae/cors_plug#46]
When I try passing an anonymous function into the `:origin` option of `CORSPlug`:

```elixir
defmodule GraphQLService.Endpoint do
  @moduledoc false

  use Phoenix.Endpoint, otp_app: :graphql_service

  use Absinthe.Phoenix.Endpoint

  plug CORSPlug, origin: fn -> "*" end

  plug Plug.Parsers,
    parsers: [ :json, :multipart, :urlencoded ],
    pass: ["*/*"],
    json_decoder: Poison

  plug Absinthe.Plug,
    schema: GraphQLService.Schema
end
```

I get the following error:

```
app_1           | == Compilation error in file lib/graphql_service/endpoint.ex ==
app_1           | ** (ArgumentError) cannot escape #Function<0.65573484/0 in :elixir_compiler_1.__MODULE__/1>. The supported values are: lists, tuples, maps, atoms, numbers, bitstrings, PIDs and remote functions in the format &Mod.fun/arity
app_1           |     (elixir) src/elixir_quote.erl:119: :elixir_quote.argument_error/1
app_1           |     (elixir) src/elixir_quote.erl:232: :elixir_quote.do_quote/3
app_1           |     (elixir) src/elixir_quote.erl:406: :elixir_quote.do_splice/5
app_1           |     (elixir) src/elixir_quote.erl:141: :elixir_quote.escape/2
app_1           |     (elixir) lib/macro.ex:479: Macro.escape/2
app_1           |     lib/plug/builder.ex:249: Plug.Builder.quote_plug_call/3
app_1           |     lib/plug/builder.ex:210: Plug.Builder.quote_plug/4
app_1           |     (elixir) lib/enum.ex:1829: Enum."-reduce/3-lists^foldl/2-0-"/3
```

After talking to some people on the Elixir Slack channel I got the impression that this isn't possible with macros. When I showed them the documentation on the README they seemed stumped as well.

I was able to pass a function into the option though.

```elixir
defmodule GraphQLService.Endpoint do
  @moduledoc false

  use Phoenix.Endpoint, otp_app: :graphql_service

  use Absinthe.Phoenix.Endpoint

  plug CORSPlug, origin: &__MODULE__.get_cors_origin/0

  plug Plug.Parsers,
    parsers: [ :json, :multipart, :urlencoded ],
    pass: ["*/*"],
    json_decoder: Poison

  plug Absinthe.Plug,
    schema: GraphQLService.Schema

  def get_cors_origin() do
    "*"
  end
end
```

The documentation is either missing some details or is possibly wrong.

**Comment by mschae** [comment]
You're right, it isn't. I apologize, I wasn't aware that this is the case. I adjusted the README accordingly, hope that works.

Unfortunately I am not aware of a way to make anonymous functions works.

**Comment by anthonator** [comment]
Sorry for not bringing this up earlier, but I think the documentation is still wrong.

I don't think functions are scoped by default to the calling module.

I believe this will throw an error:

```elixir
plug CORSPlug, origin: &my_fun/0
```

It would need to be something like this:

```elixir
plug CORSPlug, origin: &__MODULE__.my_fun/0
```

**Comment by mschae** [comment]
@anthonator I should really test my docu before publishing it... This is totally my bad. Sorry and thanks for letting me know!

**Comment by anthonator** [comment]
Not a problem. Just glad I could help! 😄
